import {createRequire} from 'node:module';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'/Users/joaomorais/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=resolve(new URL('..',import.meta.url).pathname);
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1050,height:900}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.route('http://fecho.test/**',async route=>{
 const pathname=new URL(route.request().url()).pathname;
 if(pathname==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="pt"><head><link rel="stylesheet" href="/modules/agenda-visual.css"></head><body><section id="gcAgendaWorkspace"><div id="test-host" style="max-width:760px;margin:20px auto;padding:12px"></div></section></body></html>'});
 try{await route.fulfill({contentType:extname(pathname)==='.css'?'text/css':'text/javascript',body:await readFile(resolve(root,'.'+pathname),'utf8')});}catch(_){await route.fulfill({status:404,body:''});}
});
await page.goto('http://fecho.test/');
await page.evaluate(async()=>{
 const {G}=await import('/modules/state.js');window.G=G;G.role='medico';
 const names=['Athletix','Filipe Cachopas','AlfraClinic','Liga dos Amigos de Santarém','Novo Cuidar'];
 const entities=names.map((nome,i)=>({id:'e'+i,clinic_id:'c'+i,nome,ativa:true,tipo:i===3?'avenca':'acto',avenca_valor:i===3?750:null}));
 G.agendaClinicIds=entities.map(e=>e.clinic_id);G.clinicsById=Object.fromEntries(entities.map(e=>[e.clinic_id,{name:e.nome}]));
 const p={full_name:'Doente fictício',nif:'123456789',address_line1:'Rua de Teste 1',postal_code:'2000-001',city:'Santarém'};
 const make=(id,i,date,type='Consulta')=>({id,entidade_id:'e'+i,patient_id:'p1',appointment_id:'a'+id,data:date,tipo_acto:type,valor:40,valor_faturado:80,appt_status:'done',financial_status:'normal',patients:p,created_at:date+'T09:00:00Z',updated_at:date+'T09:00:00Z'});
 const records=[make('r1',0,'2026-09-14'),make('r2',0,'2026-09-14','PRP'),make('r3',1,'2026-09-10'),make('r4',2,'2026-09-14'),make('r5',2,'2026-09-01'),make('r6',4,'2026-08-10'),make('r7',4,'2026-09-10')];
 const appointments=records.map(r=>({id:r.appointment_id,clinic_id:'c'+r.entidade_id.slice(1),patient_id:r.patient_id,start_at:r.data+'T10:00:00Z',status:'done',mode:'consulta'}));
 appointments.push({id:'liga1',clinic_id:'c3',start_at:'2026-09-14T10:00:00Z',status:'done',mode:'consulta'});
 const history=[{id:'paid',entidade_id:'e3',granularidade:'mensal',chave:'2026-09',data_referencia:'2026-09-01',estado:'pago'}];
 const tables={entidades_financeiras:entities,registos_financeiros:records,clinic_prices:[],appointments,controlo_faturacao:history};
 window.fixtures=tables;window.rpcCalls=[];
 window.sb={from(table){let filters=[],offset=0,last=Infinity;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},in(k,values){filters.push(r=>values.includes(r[k]));return q},gte(k,v){filters.push(r=>r[k]>=v);return q},lt(k,v){filters.push(r=>r[k]<v);return q},order(){return q},range(a,b){offset=a;last=b;return q},then(resolve){resolve({data:(tables[table]||[]).filter(r=>filters.every(f=>f(r))).slice(offset,last+1),error:null});}};return q;},async rpc(name,args){window.rpcCalls.push({name,args});for(const item of args.p_items){const old=history.find(h=>h.entidade_id===item.entidade_id&&h.granularidade===item.granularidade&&h.chave===item.chave);Object.assign(old||{},{});if(old)Object.assign(old,{enviado_contabilista_at:new Date().toISOString(),envio:{snapshot:{...args.p_snapshot,batch_id:'batch'}}});else history.push({...item,id:'history-'+history.length,estado:'enviado_contabilista',enviado_contabilista_at:new Date().toISOString(),envio:{snapshot:{...args.p_snapshot,batch_id:'batch'}}});}return {error:null};}};
 window.render=async()=>{const {renderAgendaFinance}=await import('/modules/agenda-financeiro.js');await renderAgendaFinance(document.querySelector('#test-host'),{day:'2026-09-14',clinicId:null});};
 await window.render();
});
const cards=page.locator('[data-day-clinics] .aw-fecho-card');
assert.equal(await cards.count(),3,'apenas clínicas com atividade no dia');
assert.equal(await cards.filter({hasText:'Filipe Cachopas'}).count(),0);
const ath=cards.filter({hasText:'Athletix'});
await ath.locator('[data-day]').click();
assert.match(await ath.locator('textarea').inputValue(),/uma fatura por doente/);
assert.match(await ath.locator('textarea').inputValue(),/PRP/);
assert.equal(await ath.locator('[data-save]').isDisabled(),true);
await ath.locator('[data-confirm]').check();await ath.locator('[data-save]').click();
await ath.getByText('0 atos por enviar',{exact:true}).waitFor({timeout:3000}).catch(async error=>{console.log(await page.locator('#test-host').innerText());console.log(await page.evaluate(()=>rpcCalls));throw error;});
assert.equal(await page.evaluate(()=>rpcCalls.length),1);
const alfra=cards.filter({hasText:'AlfraClinic'});
await alfra.locator('[data-day]').click();
await page.locator('dialog').waitFor();await page.locator('dialog [data-choice="month"]').click();
await alfra.getByText('2 atos por enviar',{exact:true}).waitFor();await alfra.locator('[data-day]').click();
assert.match(await alfra.locator('textarea').inputValue(),/01\/09\/2026 a 14\/09\/2026/);
const liga=cards.filter({hasText:'Liga dos Amigos'});
assert.match(await liga.innerText(),/Avença por enviar/);
await liga.locator('[data-day]').click();assert.match(await liga.locator('textarea').inputValue(),/750/);
await page.locator('.aw-fecho-other>summary').click();
await page.locator('[data-other-clinic]').selectOption('c4');
await page.locator('[data-other-start]').fill('2026-08-01');await page.locator('[data-other-end]').fill('2026-09-14');
await page.locator('[data-other-load]').click();
const other=page.locator('[data-other-result]');await other.getByText('2 atos por enviar',{exact:true}).waitFor();
await other.locator('[data-day]').click();assert.match(await other.locator('textarea').inputValue(),/01\/08\/2026 a 14\/09\/2026/);
// A newly completed act remains pending even after that day's earlier email.
await page.evaluate(async()=>{const r={...fixtures.registos_financeiros[0],id:'new',appointment_id:'anew'};fixtures.registos_financeiros.push(r);fixtures.appointments.push({...fixtures.appointments[0],id:'anew'});await render();});
await cards.filter({hasText:'Athletix'}).getByText('1 ato por enviar',{exact:true}).waitFor();
await page.evaluate(async()=>{fixtures.appointments.push({id:'future',clinic_id:'c2',start_at:'2026-09-28T10:00:00Z',status:'scheduled',mode:'consulta'});await render();});
assert.equal(await cards.filter({hasText:'AlfraClinic'}).locator('.aw-fecho-notice').count(),0);
await page.evaluate(async()=>{G.role='rececionista';await render();});assert.equal(await page.locator('#test-host').innerText(),'');
await page.evaluate(async()=>{G.role='medico';fixtures.appointments=fixtures.appointments.filter(a=>a.id!=='future');await render();});
await mkdir(resolve(root,'artifacts'),{recursive:true});
await page.screenshot({path:resolve(root,'artifacts/fecho-contabilidade-desktop.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'sem transbordo horizontal no telemóvel');
await page.screenshot({path:resolve(root,'artifacts/fecho-contabilidade-mobile.png'),fullPage:true});
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: clínicas do dia, faturas individuais, confirmação, histórico, mês, dois meses, avença paga, novos atos, aviso, permissões e mobile.');
