import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_PATH||'/private/tmp/gc-fecho-sql-test/node_modules/@electric-sql/pglite/dist/index.js');
const db=new PGlite();
const clinic='00000000-0000-0000-0000-000000000001',entity='00000000-0000-0000-0000-000000000002',record='00000000-0000-0000-0000-000000000003',user='00000000-0000-0000-0000-000000000004';
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql as 'select nullif(current_setting(''test.user'',true),'''')::uuid';
create table clinic_members(user_id uuid,clinic_id uuid,role text,is_active boolean);
create table clinics(id uuid primary key);
create table entidades_financeiras(id uuid primary key,clinic_id uuid,tipo text);
create table appointments(id uuid primary key,status text);
create table registos_financeiros(id uuid primary key,entidade_id uuid,appointment_id uuid,data date,appt_status text,financial_status text,created_at timestamptz,updated_at timestamptz);
create table controlo_faturacao(id uuid default gen_random_uuid(),entidade_id uuid,granularidade text,chave text,data_referencia date,registo_financeiro_id uuid,estado text,enviado_contabilista_at timestamptz,recibo_emitido_at timestamptz,pago_at timestamptz,unique(entidade_id,granularidade,chave));
select set_config('test.user','${user}',false);
insert into clinics values('${clinic}');
insert into clinic_members values('${user}','${clinic}','medico',true);
insert into entidades_financeiras values('${entity}','${clinic}','acto');
insert into registos_financeiros values('${record}','${entity}',null,'2026-01-01','done','normal','2026-01-01','2026-01-01');`);
await db.exec(await readFile(new URL('../supabase/migrations/20260914131129_agenda_fecho_contabilidade.sql',import.meta.url),'utf8'));
const item={entidade_id:entity,granularidade:'registo',chave:record,data_referencia:'2026-01-01',registo_financeiro_id:record};
const snapshot={recipient:'mariasantosp.pt@gmail.com',subject:'Teste fictício',body:'Não enviar. Teste local.',clinic_id:clinic,record_versions:{[record]:'2026-01-01T00:00:00Z'}};
const send=(items=[item],snap=snapshot)=>db.query('select agenda_confirmar_envio($1::jsonb,$2::jsonb)',[JSON.stringify(items),JSON.stringify(snap)]);
await send();
assert.equal((await db.query('select estado from controlo_faturacao')).rows[0].estado,'enviado_contabilista');
assert.equal((await db.query('select snapshot->>\'body\' as body from agenda_envios_faturacao')).rows[0].body,snapshot.body);
await assert.rejects(send(),/já foi enviado/);
await db.exec('delete from controlo_faturacao;');
await assert.rejects(send([item,item]),/já foi enviado/);
assert.equal((await db.query('select count(*)::int as n from controlo_faturacao')).rows[0].n,0,'lote revertido por inteiro');
await db.exec(`insert into controlo_faturacao(entidade_id,granularidade,chave,data_referencia,estado,pago_at) values('${entity}','registo','${record}','2026-01-01','pago','2026-01-02');`);
await send();
assert.equal((await db.query('select estado from controlo_faturacao')).rows[0].estado,'pago','preserva pagamento ao confirmar envio');
await db.exec('delete from controlo_faturacao;');
await assert.rejects(send([item],{...snapshot,record_versions:{[record]:'2026-01-02T00:00:00Z'}}),/mudou/);
await db.exec("update clinic_members set is_active=false;");await assert.rejects(send(),/Sem permissão/);
await db.exec("update clinic_members set is_active=true; update registos_financeiros set appt_status='no_show';");await assert.rejects(send(),/ato foi alterado/);
await db.exec(`update entidades_financeiras set tipo='avenca';`);
const monthly={entidade_id:entity,granularidade:'mensal',chave:'2026-01',data_referencia:'2026-01-01',registo_financeiro_id:null};
await send([monthly]);await assert.rejects(send([monthly]),/já foi enviado/);
await db.exec('grant usage on schema public, auth to authenticated; grant select on clinic_members to authenticated; set role authenticated;');
assert.ok((await db.query('select id from agenda_envios_faturacao')).rows.length>0,'médico da clínica lê os seus envios');
await db.exec("select set_config('test.user','00000000-0000-0000-0000-000000000099',false);");
assert.equal((await db.query('select id from agenda_envios_faturacao')).rows.length,0,'outro utilizador não lê dados fiscais dos doentes');
await assert.rejects(db.query('insert into agenda_envios_faturacao(clinic_id,snapshot) values($1,$2)',[clinic,'{}']),/row-level security/);
await db.close();console.log('PASS: SQL executado em base temporária; gravação, snapshot, duplicação, lote atómico, pagamento, versões, permissões, faltas e avença mensal.');
