import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {PGlite} from '../../sql-check/node_modules/@electric-sql/pglite/dist/index.js';
const db=new PGlite();
const owner='32a24abe-cd69-42d9-bf3a-3355f4f6e28c',other='00000000-0000-0000-0000-000000000002',patient='00000000-0000-0000-0000-000000000010',clinic='00000000-0000-0000-0000-000000000020',rx='00000000-0000-0000-0000-000000000030';
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table auth.users(id uuid primary key);insert into auth.users values('${owner}'),('${other}');
create table public.patients(id uuid primary key);create table public.clinics(id uuid primary key);
create table public.patient_clinic(patient_id uuid,clinic_id uuid);
create table public.wo_prescriptions(id uuid primary key,patient_id uuid,clinic_id uuid,created_at timestamptz,status text,data jsonb);
create table public.intake_tokens(id uuid primary key,patient_id uuid,clinic_id uuid,created_at timestamptz,questionnaire_type text,status text);
insert into patients values('${patient}');insert into clinics values('${clinic}');insert into patient_clinic values('${patient}','${clinic}');
insert into wo_prescriptions values('${rx}','${patient}','${clinic}',clock_timestamp()-interval '30 days','active','{"sessions":[]}');
grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;grant select on patient_clinic,wo_prescriptions,intake_tokens to authenticated;`);
await db.exec(await readFile(new URL('../supabase/migrations/20260916051444_exercise_followup_home.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009050530_followup_episode_events.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261009054631_followup_task_decisions.sql',import.meta.url),'utf8'));
const originals=await db.query('select * from wo_prescriptions');
const asUser=async uid=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${uid}',false);`);
const decision=async({episode=null,event=null,action,reason='Decisão de teste',kind=null,isTest=false,date=null}={})=>(await db.query(`select public.record_followup_episode_decision($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7,$8,$9::date) as id`,[patient,clinic,episode,event,action,reason,kind,isTest,date])).rows[0].id;
await asUser(owner);
await assert.rejects(()=>decision({action:'start'}),/Já existe/);
const close=await decision({action:'interrupted',kind:'abandonment'});
let history=(await db.query('select * from wo_followup_episode_events order by created_at,id')).rows;assert.equal(history.length,1);assert.equal(history[0].started_at,null);assert.equal(history[0].interruption_kind,'abandonment');assert.deepEqual(history[0].prescription_ids,[rx]);
const episode=history[0].episode_id;
await assert.rejects(()=>decision({episode,event:other,action:'start'}),/alterado/);
const start=await decision({episode,event:close,action:'start',reason:'Regresso'});
history=(await db.query('select * from wo_followup_episode_events order by created_at,id')).rows;assert.equal(history.length,2);const fresh=history.find(e=>e.id===start);assert.notEqual(fresh.episode_id,episode);assert.deepEqual(fresh.prescription_ids,[]);assert.equal(fresh.state,'active');assert(fresh.started_at);
await assert.rejects(()=>decision({episode,event:close,action:'start'}),/Já existe/);
await decision({episode,event:close,action:'archived'});
assert.equal((await db.query("select count(*)::int as n from wo_followup_episode_events where state='active'")).rows[0].n,1);
await assert.rejects(()=>decision({episode,event:close,action:'completed'}),/alterado/);
await assert.rejects(()=>decision({episode:fresh.episode_id,event:start,action:'completed',date:'2000-01-01'}),/Data/);
await assert.rejects(()=>decision({episode:fresh.episode_id,event:start,action:'completed',date:'2100-01-01'}),/Data/);
await assert.rejects(()=>decision({episode:fresh.episode_id,event:start,action:'completed',reason:' '}),/obrigatórios/);
await assert.rejects(()=>db.query('update wo_followup_episode_events set reason=$1',['Alterado']),/permission denied/);
await assert.rejects(()=>db.exec('delete from wo_followup_episode_events'),/permission denied/);
await asUser(other);assert.equal((await db.query('select * from wo_followup_episode_events')).rows.length,0);
await assert.rejects(()=>decision({action:'archived',isTest:true}),/Acesso/);
await assert.rejects(()=>db.query(`insert into wo_followup_episode_events(episode_id,patient_id,clinic_id,state,reason,started_at) values(gen_random_uuid(),$1,$2,'active','Teste',clock_timestamp())`,[patient,clinic]),/row-level security/);
await db.exec('reset role;set role anon;');await assert.rejects(()=>db.query('select * from wo_followup_episode_events'),/permission denied/);
await db.exec('reset role;');assert.deepEqual(await db.query('select * from wo_prescriptions'),originals);
// Importação de um encerramento legado: cria histórico e nova retoma atomically.
await db.exec('truncate wo_followup_episode_events');await asUser(owner);await db.query(`insert into wo_followup_events(patient_id,clinic_id,kind,state,reason) values($1,$2,'state','completed','Conclusão anterior')`,[patient,clinic]);await decision({action:'start'});history=(await db.query('select * from wo_followup_episode_events')).rows;assert.equal(history.length,2);assert(history.some(e=>e.state==='completed'));assert(history.some(e=>e.state==='active'));
await asUser(owner);
const task=async(expected,choice)=>db.query('select record_followup_task_decision($1::uuid,$2::uuid,null,$3,$4,$5::uuid,$6,$7) as id',[patient,clinic,'log:test','version',expected,choice,'Nota clínica']);
const contact=(await task(null,'contact')).rows[0].id;
await assert.rejects(()=>task(null,'closed'),/alterada/);
await task(contact,'closed');
const decisions=(await db.query("select decision from wo_followup_events where source_key='log:test' order by created_at")).rows;assert.deepEqual(decisions.map(r=>r.decision),['contact','closed']);
await asUser(other);await assert.rejects(()=>task(null,'contact'),/Acesso/);
await db.close();console.log('Base de dados local: episódios, retoma, histórico, datas, concorrência otimista e acesso verificados. Sem alterações na base real.');
