import {createRequire} from 'node:module';import {readFile,mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('/Users/joaomorais/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=resolve(new URL('..',import.meta.url).pathname),browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1360,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://followup.test/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="pt"><head></head><body style="background:#eff4f9;font-family:Arial;padding:24px"></body></html>'});try{await route.fulfill({contentType:extname(path)==='.css'?'text/css':'text/javascript',body:await readFile(resolve(root,'.'+path),'utf8')})}catch{await route.fulfill({status:404,body:''})}});await page.goto('http://followup.test/');
await page.evaluate(async()=>{
 const {G}=await import('/modules/state.js');window.G=G;G.sessionUser={id:'32a24abe-cd69-42d9-bf3a-3355f4f6e28c'};window.calls=[];window.writes=[];window.fail=false;window.delay=0;
 const patient=(id,name)=>({patient_id:id,clinic_id:'c1',patients:{full_name:name}}),future=new Date(Date.now()+3*86400000).toISOString().slice(0,10);
 window.tables={wo_prescriptions:[{...patient('l','Luís Portela'),id:'rx1',status:'active',created_at:'2026-09-15',expires_at:'2030-01-01',data:{sessions:[{session_id:'1',date:future}]}},{...patient('t','Tomás Morais'),id:'rx2',status:'active',created_at:'2026-09-15',expires_at:'2030-01-01',data:{sessions:[{session_id:'2',date:future}]}},{...patient('t','Tomás Morais'),id:'rx3',status:'active',created_at:'2026-08-15',expires_at:'2026-08-20',data:{sessions:[]}}],intake_tokens:[{...patient('m','Manuel Trindade'),id:'q1',questionnaire_type:'pre_consulta_v2',status:'pending_rgpd',created_at:'2026-08-23',expires_at:'2026-09-06'},{...patient('t','Tomás Morais'),id:'q2',questionnaire_type:'pre_consulta_v2',status:'pending_rgpd',created_at:'2026-09-15',expires_at:'2030-01-01'}],wo_followup_events:[],wo_session_logs:[{id:'log',prescription_id:'rx1',clinic_id:'c1',session_id:'s0',logged_at:'2026-09-12',rpe:9,note:'Nota de teste'}],wo_session_readiness:[],patient_diary_entries:[],alerts:[]};
 window.sb={from(table){let conditions=[],range=null,payload=null;const q={select(){return q},in(k,vs){conditions.push(r=>vs.includes(r[k]));return q},like(k,v){conditions.push(r=>String(r[k]).startsWith(v.replace('%','')));return q},order(){return q},range(a,b){range=[a,b];return q},insert(v){payload=v;return q},single(){return q},async then(ok,no){calls.push(table);const d=window.delay;if(d)await new Promise(r=>setTimeout(r,d));if(window.fail)return ok({data:null,error:{message:'Falha simulada'}});if(payload){const row={...payload,id:'e'+writes.length,created_at:new Date().toISOString()};writes.push(row);tables[table].push(row);return ok({data:{id:row.id},error:null})}let rows=(tables[table]||[]).filter(r=>conditions.every(c=>c(r)));if(range)rows=rows.slice(range[0],range[1]+1);return ok({data:rows,error:null})}};return q}};
 const ui=await import('/modules/home-dashboard.js');document.body.innerHTML='<style>'+ui.homeDashboardStyles()+'</style>'+ui.homeDashboardHtml();window.m=await import('/modules/exercicio/followup-home.js');window.options={clinics:[{id:'c1',name:'Clínica A'},{id:'c2',name:'Clínica B'}],clinicIds:['c1'],onOpen:item=>window.opened=item};await m.loadExerciseHome(options);
});
await mkdir(root+'/validation',{recursive:true});await page.screenshot({path:root+'/validation/inicio-inicial.png',fullPage:true});
assert.equal(await page.locator('.gc-fh-row').count(),3);assert.equal(await page.locator('.gc-fh-patient strong').filter({hasText:'Tomás'}).count(),1);
await page.locator('[data-open="l:c1"]').click();assert.equal(await page.evaluate(()=>writes.length),0);assert.deepEqual(await page.evaluate(()=>opened),{patientId:'l',clinicId:'c1'});
await page.locator('[data-filter="contact"]').click();assert.equal(await page.locator('.gc-fh-row').count(),1);await page.locator('[data-manage="m:c1"]').click();await page.locator('[name="state"]').selectOption('paused');await page.locator('[name="reason"]').fill('Pausa de teste');await page.locator('.gc-fh-editor [type=submit]').click();await page.waitForFunction(()=>writes.length===1);await page.locator('[data-state-filter]').selectOption('paused');assert.equal(await page.locator('.gc-fh-row').count(),1);
await page.locator('[data-state-filter]').selectOption('current');await page.locator('[data-search]').fill('Luís');await page.locator('.gc-fh-signals summary').click();await page.locator('[data-review]').first().click();await page.locator('.gc-fh-editor [type=submit]').click();await page.waitForFunction(()=>writes.length===2);assert.equal(await page.evaluate(()=>writes[1].kind),'review');
await page.locator('[data-search]').fill('');await page.setViewportSize({width:390,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await mkdir('/Users/joaomorais/Documents/Codex/gc-inicio-seguimento-20260916/validation',{recursive:true});await page.setViewportSize({width:1360,height:1050});await page.screenshot({path:root+'/validation/inicio.png',fullPage:true});
// Failure is explicit, no false zero. Retry restores real data.
await page.evaluate(async()=>{fail=true;await m.loadExerciseHome(options)});assert.match(await page.locator('#gcExerciseHome').innerText(),/Não foi possível/);await page.evaluate(()=>{fail=false});await page.locator('[data-retry]').click();await page.waitForSelector('.gc-fh-row');
// An old clinic request must not overwrite the new selection.
await page.evaluate(async()=>{delay=30;const old=m.loadExerciseHome(options);delay=0;await m.loadExerciseHome({...options,clinicIds:['c2']});await old});assert.equal(await page.locator('.gc-fh-row').count(),0);
// Care returns to Home and still blocks departure with unsaved clinical changes.
await page.evaluate(async()=>{const feed=await import('/modules/feed-panel.js');window.feed=feed;document.body.insertAdjacentHTML('beforeend','<div class="gc-content"></div>');window.__gc_renderCurrentView=async()=>{window.returned=G.currentView};feed.openAcompanhamentoPanel('l','c1');});
assert.equal(await page.evaluate(()=>G.currentView),'home');
await page.evaluate(async()=>{const f=document.getElementById('gcFeedPanelIframe');f.contentWindow.__gc_canLeaveCare=()=>false;window.blocked=await feed.openAcompanhamentoList()});assert.equal(await page.evaluate(()=>blocked),false);
await page.evaluate(async()=>{document.getElementById('gcFeedPanelIframe').contentWindow.__gc_canLeaveCare=()=>true;await feed.openAcompanhamentoList()});assert.equal(await page.evaluate(()=>returned),'home');
await page.evaluate(async()=>{calls.length=0;G.sessionUser={id:'other'};await m.loadExerciseHome(options)});assert.equal(await page.evaluate(()=>calls.length),0);assert.equal(await page.locator('#gcExerciseHome').isVisible(),false);assert.deepEqual(errors,[]);await browser.close();console.log('Browser: lista, filtros, abertura sem escrita, estados, revisão, erro, concorrência, acesso e largura móvel verificados.');
