import {createRequire} from 'node:module';import {readFile,mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('/Users/joaomorais/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=resolve(new URL('..',import.meta.url).pathname),browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1360,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://followup.test/**',async route=>{const path=new URL(route.request().url()).pathname;if(path==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="pt"><head></head><body style="background:#eff4f9;font-family:Arial;padding:24px"></body></html>'});try{await route.fulfill({contentType:extname(path)==='.css'?'text/css':'text/javascript',body:await readFile(resolve(root,'.'+path),'utf8')})}catch{await route.fulfill({status:404,body:''})}});await page.goto('http://followup.test/');
await page.evaluate(async()=>{
 const {G}=await import('/modules/state.js');window.G=G;G.sessionUser={id:'32a24abe-cd69-42d9-bf3a-3355f4f6e28c'};window.calls=[];window.writes=[];window.fail=false;window.delay=0;
 const patient=(id,name)=>({patient_id:id,clinic_id:'c1',patients:{full_name:name}}),future=new Date(Date.now()+3*86400000).toISOString().slice(0,10);
 window.tables={wo_prescriptions:[{...patient('l','Luís Portela'),id:'rx1',status:'active',created_at:'2026-09-15',expires_at:'2030-01-01',data:{sessions:[{session_id:'1',date:future}]}},{...patient('t','Tomás Morais'),id:'rx2',status:'active',created_at:'2026-09-15',expires_at:'2030-01-01',data:{sessions:[{session_id:'2',date:future}]}},{...patient('t','Tomás Morais'),id:'rx3',status:'active',created_at:'2026-08-15',expires_at:'2026-08-20',data:{sessions:[]}}],intake_tokens:[{...patient('m','Manuel Trindade'),id:'q1',questionnaire_type:'pre_consulta_v2',status:'pending_rgpd',created_at:'2026-08-23',expires_at:'2026-09-06'},{...patient('t','Tomás Morais'),id:'q2',questionnaire_type:'pre_consulta_v2',status:'pending_rgpd',created_at:'2026-09-15',expires_at:'2030-01-01'}],wo_followup_events:[],wo_followup_episode_events:[],wo_session_logs:[{id:'log',prescription_id:'rx1',clinic_id:'c1',session_id:'s0',logged_at:'2026-09-12',rpe:9,note:'Nota de teste'}],wo_session_readiness:[],patient_diary_entries:[],alerts:[]};
 window.sb={async rpc(name,p){if(name==='record_followup_task_decision'){if(window.fail)return {error:{message:'Falha'},data:null};const row={id:'review-'+writes.length,patient_id:p.p_patient_id,clinic_id:p.p_clinic_id,episode_id:p.p_episode_id,kind:'review',decision:p.p_decision,reason:p.p_reason,source_key:p.p_source_key,source_version:p.p_source_version,created_at:new Date().toISOString()};writes.push(row);tables.wo_followup_events.push(row);return {data:row.id,error:null}}if(window.fail)return {data:null,error:{message:'Falha simulada'}};const previous=tables.wo_followup_episode_events.filter(e=>e.episode_id===p.p_episode_id).at(-1);const isStart=p.p_action==='start';const row={id:'episode-event-'+writes.length,episode_id:isStart?'episode-'+writes.length:previous?.episode_id||'episode-'+writes.length,patient_id:p.p_patient_id,clinic_id:p.p_clinic_id,state:isStart?'active':p.p_action,interruption_kind:p.p_interruption_kind,is_test:p.p_is_test,reason:p.p_reason,started_at:isStart?new Date().toISOString():previous?.started_at||null,closed_at:isStart?null:previous?.closed_at||new Date().toISOString(),prescription_ids:isStart?[]:tables.wo_prescriptions.filter(r=>r.patient_id===p.p_patient_id&&r.clinic_id===p.p_clinic_id).map(r=>r.id),questionnaire_ids:isStart?[]:tables.intake_tokens.filter(r=>r.patient_id===p.p_patient_id&&r.clinic_id===p.p_clinic_id).map(r=>r.id),created_at:new Date().toISOString()};writes.push({...row,rpc:name});tables.wo_followup_episode_events.push(row);return {data:row.id,error:null}},from(table){let conditions=[],range=null,payload=null;const q={select(){return q},in(k,vs){conditions.push(r=>vs.includes(r[k]));return q},like(k,v){conditions.push(r=>String(r[k]).startsWith(v.replace('%','')));return q},order(){return q},range(a,b){range=[a,b];return q},insert(v){payload=v;return q},single(){return q},async then(ok,no){calls.push(table);const d=window.delay;if(d)await new Promise(r=>setTimeout(r,d));if(window.fail)return ok({data:null,error:{message:'Falha simulada'}});if(payload){const row={...payload,id:'e'+writes.length,created_at:new Date().toISOString()};writes.push(row);tables[table].push(row);return ok({data:{id:row.id},error:null})}let rows=(tables[table]||[]).filter(r=>conditions.every(c=>c(r)));if(range)rows=rows.slice(range[0],range[1]+1);return ok({data:rows,error:null})}};return q}};
 const ui=await import('/modules/home-dashboard.js');document.body.innerHTML='<style>'+ui.homeDashboardStyles()+'</style>'+ui.homeDashboardHtml();window.m=await import('/modules/exercicio/followup-home.js');window.options={clinics:[{id:'c1',name:'Clínica A'},{id:'c2',name:'Clínica B'}],clinicIds:['c1'],onOpen:item=>window.opened=item};await m.loadExerciseHome(options);
});
await mkdir(root+'/validation',{recursive:true});
assert.equal(await page.locator('.gc-fh-tabs button').count(),5);
assert.equal(await page.locator('.gc-fh-row').count(),3);assert.equal(await page.locator('.gc-fh-patient strong').filter({hasText:'Tomás'}).count(),1);
await page.locator('[data-open="l:c1:legacy"]').click();assert.equal(await page.evaluate(()=>writes.length),0);assert.deepEqual(await page.evaluate(()=>opened),{patientId:'l',clinicId:'c1'});
await page.locator('[data-filter="attention"]').click();assert.equal(await page.locator('.gc-fh-row').count(),3);
// Interruption records a decision without mutating source prescriptions.
const sources=await page.evaluate(()=>JSON.stringify([tables.wo_prescriptions,tables.intake_tokens,tables.wo_session_logs]));
await page.locator('[data-manage="l:c1:legacy"]').click();assert.equal(await page.locator('.gc-fh-row .gc-fh-compact').count(),1);assert.equal(await page.locator('[data-fields]').isVisible(),false);assert.equal(await page.locator('.gc-fh-compact select').count(),0);await page.locator('[data-episode-action=interrupted]').click();await page.locator('[data-interruption-choice=abandonment]').click();await page.locator('[name="reason"]').fill('Abandono confirmado — exemplo de teste');await page.locator('.gc-fh-editor [type=submit]').click();await page.waitForFunction(()=>writes.length===1);await page.waitForSelector('[data-filter="interrupted"]');
await page.locator('[data-filter="interrupted"]').click();assert.equal(await page.locator('.gc-fh-row').count(),1);assert.match(await page.locator('.gc-fh-row').innerText(),/Interrompido — abandono/);
await page.locator('[data-history="l"]').first().click();await page.locator('.gc-fh-history').first().locator('summary').first().click();assert.match(await page.locator('[data-editor]').innerText(),/Nota de teste/);assert.equal(await page.evaluate(()=>writes.length),1);
await page.locator('[data-close-editor]').click();
await page.locator('#gcExerciseHome').screenshot({path:root+'/validation/acompanhamento-interrompidos.png'});
await page.locator('[data-reactivate]').click();assert.match(await page.locator('.gc-fh-editor').innerText(),/novo episódio/);await page.locator('[name="reason"]').fill('Retoma do acompanhamento');await page.locator('.gc-fh-editor [type=submit]').click();await page.waitForFunction(()=>writes.length===2);await page.waitForSelector('[data-filter="current"][aria-pressed="true"]');assert.equal(await page.locator('.gc-fh-row').count(),3);
await page.locator('[data-history="l"]').first().click();assert.equal(await page.locator('.gc-fh-history').count(),2);await page.locator('[data-close-editor]').click();
const currentLuis=page.locator('.gc-fh-row').filter({hasText:'Luís Portela'});assert.match(await currentLuis.innerText(),/Novo episódio/);assert(!((await currentLuis.innerText()).includes('Nota de teste')));
// Review historical signals remains explicit and versioned.
await page.locator('[data-filter="interrupted"]').click();await page.locator('[data-history="l"]').first().click();await page.locator('.gc-fh-history').filter({hasText:'Interrompido — abandono'}).locator('summary').first().click();await page.locator('.gc-fh-history').filter({hasText:'Interrompido — abandono'}).locator('.gc-fh-signals summary').first().click();await page.locator('.gc-fh-history').filter({hasText:'Interrompido — abandono'}).locator('[data-review]').first().click();assert.match(await page.locator('.gc-fh-editor').innerText(),/Nota de teste/);await page.locator('[name=decision]').selectOption('closed');await page.locator('[name=reason]').fill('Resposta revista; sem alteração');await page.locator('.gc-fh-editor [type=submit]').click();await page.waitForFunction(()=>writes.length===3);assert.equal(await page.evaluate(()=>writes[2].kind),'review');
// Test records leave active counters and remain in archive.
await page.locator('[data-filter="current"]').click();await page.locator('[data-manage="m:c1:legacy"]').click();await page.locator('[data-episode-action=archived]').click();await page.locator('[name="reason"]').fill('Registo fictício de teste');await page.locator('.gc-fh-editor [type=submit]').click();await page.waitForFunction(()=>writes.length===4);await page.locator('[data-filter="archived"]').click();assert.equal(await page.locator('.gc-fh-row').count(),1);assert.match(await page.locator('.gc-fh-row').innerText(),/Teste/);
assert.equal(await page.evaluate(()=>JSON.stringify([tables.wo_prescriptions,tables.intake_tokens,tables.wo_session_logs])),sources);
await page.locator('[data-filter="current"]').click();await page.locator('[data-search]').fill('Luís');assert.equal(await page.locator('.gc-fh-row').count(),1);await page.locator('[data-search]').fill('');
await page.setViewportSize({width:390,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:root+'/validation/acompanhamento-mobile.png',fullPage:true});
await page.setViewportSize({width:1360,height:1050});await page.locator('#gcExerciseHome').screenshot({path:root+'/validation/acompanhamento-em-curso.png'});
// Choosing contact keeps the task visible until an actual contact is recorded.
await page.evaluate(async()=>{tables.wo_session_logs.push({id:'contact-log',prescription_id:'rx2',clinic_id:'c1',session_id:'contact-session',logged_at:new Date().toISOString(),note:'Dor referida pelo doente',rpe:8});await m.loadExerciseHome(options)});
await page.locator('[data-filter="attention"]').click();
await page.locator('.gc-fh-row').filter({hasText:'Tomás Morais'}).locator('.gc-fh-actions [data-review]').click();
assert.match(await page.locator('.gc-fh-editor').innerText(),/Dor referida pelo doente/);
await page.locator('[name=decision]').selectOption('contact');await page.locator('[name=reason]').fill('Contactar para esclarecer sintomas');await page.locator('.gc-fh-editor [type=submit]').click();
await page.waitForSelector('.gc-fh-actions [data-review]');
await page.locator('.gc-fh-row').filter({hasText:'Tomás Morais'}).locator('.gc-fh-actions [data-review]').click();
assert.match(await page.locator('.gc-fh-editor').innerText(),/Registar contacto/);
await page.locator('[name=decision]').selectOption('closed');await page.locator('[name=reason]').fill('Contacto efetuado; orientação registada');await page.locator('.gc-fh-editor [type=submit]').click();
await page.waitForFunction(()=>writes.filter(e=>e.kind==='review').length===3);
// Failure is explicit, no false zero. Retry restores real data.
await page.evaluate(async()=>{fail=true;await m.loadExerciseHome(options)});assert.match(await page.locator('#gcExerciseHome').innerText(),/Não foi possível/);await page.evaluate(()=>{fail=false});await page.locator('[data-retry]').click();await page.waitForSelector('.gc-fh-row');
// An old clinic request must not overwrite the new selection.
await page.evaluate(async()=>{delay=30;const old=m.loadExerciseHome(options);delay=0;await m.loadExerciseHome({...options,clinicIds:['c2']});await old});assert.equal(await page.locator('.gc-fh-row').count(),0);
// Care returns to Home and still blocks departure with unsaved clinical changes.
await page.evaluate(async()=>{const feed=await import('/modules/feed-panel.js');window.feed=feed;document.body.insertAdjacentHTML('beforeend','<div class="gc-content"></div>');window.__gc_renderCurrentView=async()=>{window.returned=G.currentView};feed.openAcompanhamentoPanel('l','c1');});
assert.equal(await page.evaluate(()=>G.currentView),'home');
await page.evaluate(async()=>{const f=document.getElementById('gcFeedPanelIframe');f.contentWindow.__gc_canLeaveCare=()=>false;window.blocked=await feed.openAcompanhamentoList()});assert.equal(await page.evaluate(()=>blocked),false);
await page.evaluate(async()=>{document.getElementById('gcFeedPanelIframe').contentWindow.__gc_canLeaveCare=()=>true;await feed.openAcompanhamentoList()});assert.equal(await page.evaluate(()=>returned),'home');
await page.evaluate(async()=>{calls.length=0;G.sessionUser={id:'other'};await m.loadExerciseHome(options)});assert.equal(await page.evaluate(()=>calls.length),0);assert.equal(await page.locator('#gcExerciseHome').isVisible(),false);assert.deepEqual(errors,[]);await browser.close();console.log('Browser: cinco separadores, interrupção, reativação, histórico, testes, revisão, pesquisa, erro, concorrência, acesso e largura móvel verificados.');
