import test from 'node:test';import assert from 'node:assert/strict';import {buildFollowup} from '../modules/exercicio/followup-model.js';
const now=new Date('2026-09-16T05:00:00Z');
const rx=(id,p,expires='2026-09-25T23:00:00Z',clinic='c')=>({id,patient_id:p,clinic_id:clinic,patients:{full_name:p},created_at:'2026-09-15',status:'active',expires_at:expires,data:{sessions:[{session_id:'s',date:'2026-09-20'}]}});
const q=(id,p,status='pending_rgpd',expires='2026-09-18T23:00:00Z')=>({id,patient_id:p,clinic_id:'c',patients:{full_name:p},created_at:'2026-09-15',questionnaire_type:'pre_consulta_v2',status,expires_at:expires});
test('Uma linha por doente; prescrições antigas não duplicam; questionário não suspende plano',()=>{const rows=buildFollowup({prescriptions:[rx('a','T'),rx('b','T','2026-08-20')],questionnaires:[q('q','T')]},now);assert.equal(rows.length,1);assert.equal(rows[0].state,'active');assert.equal(rows[0].contexts[0].valid.length,1);assert(rows[0].signals.some(s=>s.label.includes('aguardar')));});
test('Questionário fora de prazo não significa abandono',()=>{assert.equal(buildFollowup({questionnaires:[q('q','M','pending_rgpd','2026-09-06')]},now)[0].state,'contact');});
test('Não mistura questionários de outras áreas',()=>{assert.equal(buildFollowup({questionnaires:[{...q('x','X'),questionnaire_type:'outro'}]},now).length,0);});
test('Questionário concluído recente substitui convite antigo sem resposta',()=>{const r=buildFollowup({questionnaires:[{...q('1','L'),created_at:'2026-08-21'},q('2','L','completed')]},now)[0];assert.equal(r.state,'prepare');assert(!r.signals.some(s=>s.kind==='questionnaire'));});
test('Sinal antigo permanece mesmo com treino posterior normal; abrir não resolve; tratar é por versão',()=>{const data={prescriptions:[rx('a','L')],logs:[{prescription_id:'a',session_id:'old',logged_at:'2026-09-12',rpe:9},{prescription_id:'a',session_id:'new',logged_at:'2026-09-15',rpe:4}]};const s=buildFollowup(data,now)[0].signals.find(s=>s.key.startsWith('log:'));assert(s);data.events=[{kind:'review',patient_id:'L',clinic_id:'c',source_key:s.key,source_version:s.version}];assert(!buildFollowup(data,now)[0].signals.some(x=>x.key===s.key));data.logs[0].note='Nova informação';assert(buildFollowup(data,now)[0].signals.some(x=>x.key===s.key));});
test('Mal-estar numérico antes do treino é sinalizado sem dor',()=>{const r=buildFollowup({prescriptions:[rx('a','L')],readiness:[{id:'r',prescription_id:'a',feeling:2,has_symptoms:false,answered_at:'2026-09-15'}]},now);assert(r[0].signals.some(s=>s.key==='readiness:r'));});
test('Fim dos treinos não é validade do link; sessões sem registo não são abandono',()=>{const a=rx('a','L','2030-01-01');a.data.sessions=[{session_id:'s',date:'2026-09-10'}];const r=buildFollowup({prescriptions:[a]},now)[0];assert.equal(r.state,'active');assert(r.signals.some(s=>s.key==='plan:none'));assert(r.signals.some(s=>s.key==='missed'));});
test('Mesmo doente em duas clínicas mantém ações no contexto correto',()=>{const rows=buildFollowup({prescriptions:[rx('a','L'),rx('b','L',undefined,'c2')]},now);assert.equal(rows.length,1);assert.equal(rows[0].contexts.length,2);assert.equal(rows[0].contexts[1].clinicId,'c2');});
test('Estado explícito exige decisão; retomar volta ao estado derivado',()=>{const data={prescriptions:[rx('a','L')],events:[{id:'1',kind:'state',state:'paused',patient_id:'L',clinic_id:'c',created_at:'2026-09-16',reason:'Viagem'}]};assert.equal(buildFollowup(data,now)[0].state,'paused');data.events.push({...data.events[0],id:'2',state:'auto',created_at:'2026-09-17'});assert.equal(buildFollowup(data,now)[0].state,'active');});

test('Pendência de questionário reaparece quando ultrapassa o prazo mesmo se antes tratada',()=>{const data={questionnaires:[q('q','M')]};const r=buildFollowup(data,now)[0].signals.find(s=>s.kind==='questionnaire');data.events=[{kind:'review',patient_id:'M',clinic_id:'c',source_key:r.key,source_version:r.version}];assert(!buildFollowup(data,now)[0].signals.some(s=>s.kind==='questionnaire'));assert(buildFollowup(data,new Date('2026-09-20')).at(0).signals.some(s=>s.kind==='questionnaire'));});
