import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=readFileSync(new URL('../modules/acompanhamento-clinico.html',import.meta.url),'utf8');
const src=readFileSync(new URL('../modules/exercicio/prescricao/prescricao.js',import.meta.url),'utf8');
const fn=(source,name,next)=>source.slice(source.indexOf(`function ${name}`),source.indexOf(`function ${next}`,source.indexOf(`function ${name}`)));
const elements=new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{textContent:'',hidden:false,disabled:false});return elements.get(id)};
const modules=[{},{}],opened=[];
const c=vm.createContext({token:'fake',accessTerminated:false,portal:{device_bound_at:'2026-09-27'},exercisePlan:{data:{endDate:'2026-10-25'}},$:el,fmt:x=>x,portalLink:()=> 'https://example.invalid/test?t=fake',document:{querySelectorAll:()=>modules},window:{open:(...a)=>opened.push(a),location:{}},encodeURIComponent});
el('phoneAccessEnded');
vm.runInContext(fn(html,'refreshAccessSummary','sharePatientAccess')+fn(html,'sharePatientAccess','markDirty'),c);
vm.runInContext('refreshAccessSummary();sharePatientAccess("whatsapp")',c);
assert.equal(el('copy').disabled,false);
assert.match(el('accessPlanEnd').textContent,/2026-10-25/);
assert.match(opened[0][0],/^https:\/\/wa.me\/\?text=/);
assert.equal(new URL(opened[0][0]).searchParams.get('text').includes('https://example.invalid/test?t=fake'),true);
vm.runInContext('accessTerminated=true;refreshAccessSummary();sharePatientAccess("whatsapp");sharePatientAccess("email")',c);
assert.equal(opened.length,1);
assert.equal(el('copy').disabled,true);
assert.equal(el('shareEmail').disabled,true);
assert.equal(el('phoneAccessEnded').hidden,false);
assert.equal(modules.every(e=>e.hidden),true);
vm.runInContext('accessTerminated=false;portal.access_expires_at="2000-01-01T00:00:00Z";refreshAccessSummary();sharePatientAccess("whatsapp")',c);
assert.equal(el('copy').disabled,true);
assert.equal(opened.length,1,'Expired links must not be shared');
vm.runInContext('portal.access_expires_at=null;refreshAccessSummary()',c);
assert.equal(el('copy').disabled,false,'Removing expiry restores sharing');
const inclusion=vm.createContext({accessClinicalState:{pathology:{on:true},activity:{on:true},diary:{on:false}},portal:{access_modules:{pathology:false}}});
vm.runInContext(fn(html,'accessIncluded','accessCard'),inclusion);
assert.equal(vm.runInContext('accessIncluded("pathology")',inclusion),false);
assert.equal(vm.runInContext('accessIncluded("activity")',inclusion),true);
assert.equal(vm.runInContext('accessIncluded("diary")',inclusion),false,'Availability never invents a clinical prescription');
const events={},pending=[],buttons=[];let timer;
const input={isConnected:true,textContent:'',addEventListener:(n,f)=>events[n]=f};
const host={style:{},innerHTML:'',querySelectorAll:()=>buttons};
const searches=[];
const p=vm.createContext({document:{getElementById:id=>id==='gcwoPatientQuery'?input:host},setTimeout:f=>(timer=f,1),clearTimeout:()=>{},sb:{rpc:(name,args)=>{searches.push(args);return new Promise(r=>pending.push(r))}},_state:{clinicId:'clinic'},G:{clinics:[]},escHtml:x=>x,escAttr:x=>x,console});
p.window={sb:p.sb};
vm.runInContext(fn(src,'wirePatientPicker','renderPatientBanner'),p);
vm.runInContext('wirePatientPicker()',p);
input.textContent='Ana';events.input();const first=timer();
input.textContent='Maria';events.input();const second=timer();
pending[1]({data:[{id:'m',full_name:'Maria'}]});await second;
assert.match(host.innerHTML,/Maria/);
pending[0]({data:[{id:'a',full_name:'Ana'}]});await first;
assert.doesNotMatch(host.innerHTML,/Ana/);
assert.equal(searches[0].p_clinic_id,'clinic');
input.textContent='x';events.input();await timer();assert.equal(host.style.display,'none');
console.log('Pesquisa concorrente, filtro da clínica, ligação ativa e bloqueio de envio após término: OK');
