import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const load = source => import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const helperSource = readFileSync(new URL('../modules/relatorios/_shared/doctor-signature.js', import.meta.url), 'utf8');
const helperUrl = 'data:text/javascript;base64,' + Buffer.from(helperSource).toString('base64');
const source = readFileSync(new URL('../modules/pedidos/pedidos-v2.js', import.meta.url), 'utf8');
const start = source.indexOf('async function renderPdfViaProxy(html) {');
assert.ok(start >= 0);
const end = source.indexOf('\n}', start) + 2;
const { renderPdfViaProxy } = await load(`import { fetchPrivatePdf } from '${helperUrl}';\nconst PDF_PROXY_URL='https://gc-pdf-proxy.dr-joao-morais.workers.dev/pdf';\nconst MIN_PDF_BYTES=5000;\nexport ${source.slice(start, end)}`);
let calls = 0;
globalThis.window = {sb:{auth:{getSession:async()=>({data:{session:{access_token:'session-test-only'}}})}}};
globalThis.fetch = async (url, options) => {
 calls++;
 assert.equal(options.headers.get('Authorization'), 'Bearer session-test-only');
 assert.equal(options.headers.get('content-type'), 'application/json');
 assert.equal(JSON.parse(options.body).media, 'print');
 assert.equal(JSON.parse(options.body).html, '<p>Exame fictício</p>');
 return new Response('%PDF-' + '0'.repeat(6000), {headers:{'content-type':'application/pdf'}});
};
assert.ok((await renderPdfViaProxy('<p>Exame fictício</p>')).size > 5000);
window.sb.auth.getSession = async()=>({data:{session:null}});
await assert.rejects(renderPdfViaProxy('<p>Exame fictício</p>'), /Inicie sessão/);
assert.equal(calls, 1, 'Sessão ausente não deve enviar o documento');
window.sb.auth.getSession = async()=>({data:{session:{access_token:'session-test-only'}}});
globalThis.fetch = async()=>new Response('Acesso recusado', {status:403});
await assert.rejects(renderPdfViaProxy('<p>Exame fictício</p>'), /403/);
globalThis.fetch = async()=>new Response('%PDF-too-small');
await assert.rejects(renderPdfViaProxy('<p>Exame fictício</p>'), /demasiado pequeno/);
console.log('PASS: sessão enviada pelo emissor real de Pedidos; ausência de sessão, recusa do servidor e PDF inválido tratados.');
