/* Config de questionário — Pré-Consulta. Lido pelo intake-motor.js. Só dados, zero lógica. */

export default {
  id: 'pre_consulta',
  titulo: 'Questionário Pré-Consulta',
  subtitle: 'Preenchimento antes da primeira consulta',

  seccoes: [
    { id: 'identificacao', titulo: 'Identificação',
      perguntas: [
        { id: 's1_nome', tipo: 'texto_curto', label: 'Nome completo', obrigatorio: true },
      ],
    },

    { id: 'expectativas', titulo: 'Expectativas e Objetivos',
      perguntas: [
        { id: 's2_incomoda', tipo: 'escolha_multipla', label: 'O que mais incomoda na sua saúde atualmente?', max: 3,
          opcoes: ['Excesso de peso', 'Falta de energia e fadiga crónica', 'Má qualidade do sono', 'Ansiedade ou stress', 'Dores articulares ou musculares', 'Digestão'],
          outro: true },
        { id: 's2_mudancas', tipo: 'escolha_multipla', label: 'Quais mudanças gostaria de ver na sua saúde e estilo de vida a médio/longo prazo?',
          opcoes: ['Perder gordura corporal', 'Ganhar massa muscular', 'Dormir melhor', 'Ter mais energia diária', 'Controlar a compulsão alimentar', 'Reduzir medicação', 'Melhorar análises clínicas'] },
        { id: 's2_descricao_objetivo', tipo: 'texto_curto', label: 'Como se descreveria se este objetivo fosse alcançado?',
          apoio: 'Descreva concretamente o que seria diferente no seu dia a dia — como se sentiria, o que conseguiria fazer que hoje não consegue.' },
        { id: 's2_nada_mudar', tipo: 'texto_curto', label: 'O que muda na sua vida diária se nada mudar?', multilinha: true,
          apoio: 'Pense nas consequências reais de manter os hábitos atuais, a curto e a longo prazo.' },
      ],
    },

    { id: 'motivacao', titulo: 'Motivação e Prontidão para Mudança',
      perguntas: [
        { id: 's3_prontidao', tipo: 'escala', label: 'Prontidão para mudar', min: 0, max: 10 },
        { id: 's3_confianca', tipo: 'escala', label: 'Confiança para manter 6 meses', min: 0, max: 10 },
        { id: 's3_confianca_subir', tipo: 'texto_curto', label: 'O que faria essa confiança subir 2 pontos?' },
        { id: 's3_origem_decisao', tipo: 'escolha_unica', label: 'Esta decisão de mudar é sua, ou vem sobretudo de terceiros?',
          opcoes: ['Minha, iniciativa própria', 'Mista (vontade própria, mas impulsionada por alguém)', 'Sobretudo de terceiros (médico, família, cônjuge)'] },
      ],
    },

    { id: 'historico_peso', titulo: 'Histórico de Peso, Dificuldades e Barreiras',
      perguntas: [
        { id: 's4_peso_atual', tipo: 'numero', label: 'Peso atual (kg)' },
        { id: 's4_peso_desejado', tipo: 'numero', label: 'Peso desejado (kg)' },
        { id: 's4_peso_maximo', tipo: 'numero', label: 'Peso máximo já atingido na vida adulta (kg)' },
        { id: 's4_ioio', tipo: 'escolha_unica', label: 'Já tentou perder peso várias vezes ou sofre de efeito ioiô?',
          opcoes: ['Sim, frequentemente (recupero sempre)', 'Algumas vezes (oscilo muito)', 'Raramente', 'Não, é a primeira vez'] },
        { id: 's4_habito_mantido', tipo: 'escolha_unica', label: 'Já manteve um hábito saudável durante mais de 3 meses seguidos?',
          opcoes: ['Sim, exercício físico', 'Sim, plano alimentar', 'Sim, rotina de sono', 'Nunca consegui manter por tanto tempo'] },
        { id: 's4_abandono', tipo: 'escolha_multipla', label: 'Na sua perspetiva, o que o(a) faz habitualmente abandonar as tentativas?', max: 3,
          opcoes: ['Fome excessiva', 'Ansiedade ou compulsão alimentar', 'Falta de tempo', 'Vida social', 'Monotonia alimentar', 'Frustração com resultados lentos', 'Falta de planeamento'],
          outro: true },
        { id: 's4_fome_emocional', tipo: 'texto_curto', label: 'Como lida com a fome emocional ou stress em relação à comida?', multilinha: true,
          apoio: 'Descreva o que costuma fazer quando sente stress, ansiedade ou tristeza relacionados com comida — por exemplo, comer mais, comer menos, ou evitar certos alimentos.' },
      ],
    },

    { id: 'alimentacao_dietas', titulo: 'Relação com a Alimentação, Dietas e Dieta Cetogénica',
      perguntas: [
        { id: 's5_dietas_passado', tipo: 'escolha_multipla', label: 'Que tipo de dietas já seguiu no passado?',
          opcoes: ['Jejum intermitente', 'Low Carb', 'Cetogénica', 'Dieta mediterrânica', 'Hipocalórica restrita', 'Contagem de calorias', 'Nunca fiz dieta específica'] },
        { id: 's5_exp_lowcarb', tipo: 'escolha_unica', label: 'Como foi a sua experiência anterior com Low Carb ou Cetogénica?',
          opcoes: ['Excelente (perdi peso e tive muita energia)', 'Boa no início, mas difícil de manter a longo prazo', 'Má (tive dores de cabeça, fadiga ou "gripe cetogénica")', 'Nunca experimentei'] },
        { id: 's5_recetividade_ceto', tipo: 'escolha_unica', label: 'Qual a sua recetividade para adotar uma estratégia cetogénica (foco em gorduras boas e proteínas)?',
          opcoes: ['Totalmente aberto(a) e motivado(a)', 'Curioso(a), mas com algumas dúvidas', 'Receoso(a) devido a restrições sociais ou hábitos', 'Prefiro não seguir'] },
        { id: 's5_receios_ceto', tipo: 'escolha_multipla', label: 'Maiores receios ou barreiras para iniciar dieta cetogénica',
          opcoes: ['Dificuldade em abolir pão/massas', 'Impacto em convívios sociais e jantares fora', 'Falta de ideias de receitas', 'Medo de falta de energia', 'Nenhum receio específico'],
          outro: true },
        { id: 's5_restricoes', tipo: 'escolha_multipla', label: 'Tem restrições alimentares?',
          opcoes: ['Nenhuma', 'Intolerância à lactose', 'Alergia ao glúten', 'Vegetariano(a)', 'Vegano(a)', 'Alergia a frutos secos ou marisco'],
          outro: true },
      ],
    },

    { id: 'atividade_fisica', titulo: 'Atividade Física e Condição Física',
      perguntas: [
        { id: 's6_nivel_atividade', tipo: 'escolha_unica', label: 'Como classifica o seu nível atual de atividade física diária (fora de treinos)?',
          opcoes: ['Sedentário(a) (passo o dia sentado/a)', 'Ligeiramente ativo(a) (caminhadas curtas, tarefas domésticas)', 'Moderadamente ativo(a) (trabalho em pé ou deslocações a pé)'] },
        { id: 's6_exercicio_estruturado', tipo: 'escolha_unica', label: 'Pratica algum tipo de exercício físico estruturado atualmente?',
          opcoes: ['Sim, regularmente (3 ou mais vezes por semana)', 'Sim, ocasionalmente', 'Não pratico atualmente'] },
        { id: 's6_dor_lesao', tipo: 'escolha_unica', label: 'Tem atualmente dor ou lesão que limite a prática de exercício?',
          opcoes: ['Sim', 'Não', 'Talvez'] },
        { id: 's6_indicacao_medica', tipo: 'escolha_unica', label: 'Já teve indicação médica prévia para evitar algum tipo de esforço ou movimento específico?',
          opcoes: ['Sim', 'Não'] },
        { id: 's6_obstaculos_exercicio', tipo: 'texto_curto', label: 'Principais obstáculos que dificultam o exercício' },
        { id: 's6_agua', tipo: 'escolha_unica', label: 'Consumo diário habitual de água',
          opcoes: ['Menos de 1L', '1L a 2L', 'Mais de 2L'] },
        { id: 's6_cafeina', tipo: 'escolha_unica', label: 'Consumo diário habitual de cafeína',
          opcoes: ['Não consumo', '1 café ou equivalente por dia', '2 a 3 cafés ou equivalentes por dia', '4 ou mais por dia'] },
        { id: 's6_dias_semana', tipo: 'numero', label: 'Quantos dias por semana gostaria de dedicar à atividade física?', min: 1, max: 7 },
        { id: 's6_duracao_sessao', tipo: 'escolha_unica', label: 'Quanto tempo, por sessão, gostaria de dedicar?',
          opcoes: ['Menos de 15 min', '15-30 min', '30-45 min', '45-60 min', 'Mais de 60 min'] },
        { id: 's6_tipos_atividade', tipo: 'escolha_multipla', label: 'Que tipos de atividade física prefere ou tem mais vontade de praticar?',
          opcoes: ['Caminhar', 'Correr', 'Nadar', 'Ciclismo', 'Ginásio/Musculação', 'TRX', 'Calistenia', 'Aulas de grupo', 'Dança', 'Yoga', 'Pilates'],
          outro: true },
      ],
    },

    { id: 'plano_inicial', titulo: 'Plano de Ação Inicial',
      perguntas: [
        { id: 's7_primeiro_habito', tipo: 'escolha_unica', label: 'Qual o primeiro hábito que gostaria de mudar já esta semana?',
          opcoes: ['Beber mais água', 'Dormir mais cedo', 'Reduzir açúcar/doces', 'Caminhar 20 minutos por dia', 'Planear as refeições da semana'],
          outro: true },
        { id: 's7_obstaculo_7dias', tipo: 'escolha_multipla', label: 'Obstáculo previsto para os primeiros 7 dias',
          opcoes: ['Falta de tempo', 'Eventos sociais', 'Tentação com doces em casa', 'Cansaço após o trabalho', 'Nenhum obstáculo previsível'],
          outro: true },
        { id: 's7_tipo_metas', tipo: 'escolha_unica', label: 'Prefere metas fixas ou flexíveis?',
          opcoes: ['Fixas', 'Flexíveis'] },
      ],
    },

    { id: 'bem_estar_social', titulo: 'Bem-Estar Social e Propósito',
      perguntas: [
        { id: 's8_refeicoes_fora', tipo: 'escolha_unica', label: 'Com que frequência faz refeições fora de casa?',
          opcoes: ['Diariamente', 'Várias vezes por semana', 'Fim de semana', 'Raramente'] },
        { id: 's8_apoio_circulo', tipo: 'escolha_unica', label: 'Sente apoio do seu círculo próximo (família/amigos) neste processo?',
          opcoes: ['Total', 'Parcial', 'Não apoiam', 'Indiferente'] },
        { id: 's8_alcool', tipo: 'escolha_unica', label: 'Qual o seu consumo de álcool?',
          opcoes: ['Nunca', 'Social', 'Várias vezes por semana', 'Diário'] },
        { id: 's8_solidao', tipo: 'escolha_unica', label: 'Sente-se só com frequência, independentemente de estar acompanhado(a)?',
          opcoes: ['Sim, com frequência', 'Às vezes', 'Raramente', 'Nunca'] },
        { id: 's8_alguem_para_falar', tipo: 'escolha_unica', label: 'Tem alguém com quem possa falar abertamente sobre dificuldades pessoais?',
          opcoes: ['Sim', 'Nem sempre', 'Não'] },
        { id: 's8_prazer_frequencia', tipo: 'escolha_unica', label: 'Com que frequência faz algo só por prazer, sem ser "produtivo"?',
          opcoes: ['Diariamente', 'Algumas vezes por semana', 'Raramente', 'Nunca'] },
        { id: 's8_atividades_prazer', tipo: 'texto_curto', label: 'Que atividades lhe dão prazer?' },
        { id: 's8_recuperacao_ecrans', tipo: 'escolha_unica', label: 'Essa estratégia de recuperação envolve comida, álcool ou ecrãs na maioria das vezes?',
          opcoes: ['Sim, na maioria das vezes', 'Às vezes', 'Raramente', 'Não'] },
        { id: 's8_sempre_quis_fazer', tipo: 'texto_curto', label: 'Há algo que sempre quis fazer e ainda não fez?' },
      ],
    },

    { id: 'ambiente_rotina', titulo: 'Ambiente, Rotina e Logística Diária',
      perguntas: [
        { id: 's9_vive_sozinho', tipo: 'escolha_unica', label: 'Vive sozinho?', opcoes: ['Sim', 'Não'] },
        { id: 's9_cozinha_trabalho', tipo: 'escolha_unica', label: 'Cozinha no trabalho?', opcoes: ['Sim', 'Não'] },
        { id: 's9_horario_trabalho', tipo: 'escolha_unica', label: 'Horário de trabalho', opcoes: ['Fixo', 'Turnos', 'Irregular'] },
        { id: 's9_regime_trabalho', tipo: 'escolha_unica', label: 'Regime de trabalho', opcoes: ['Remoto', 'Presencial', 'Misto'] },
        { id: 's9_compras_cozinha', tipo: 'escolha_unica', label: 'Quem faz as compras e cozinha habitualmente?',
          opcoes: ['Eu próprio(a) a 100%', 'Dividido com parceiro(a)/família', 'Outra pessoa faz a maior parte', 'Compro refeições prontas ou fora de casa'] },
      ],
    },

    { id: 'acompanhamento', titulo: 'Preferências de Acompanhamento',
      perguntas: [
        { id: 's10_formato', tipo: 'escolha_unica', label: 'Prefere apps, papel, ou check-in verbal para monitorizar o seu progresso?',
          opcoes: ['Aplicação/telemóvel', 'Papel', 'Check-in verbal', 'Sem preferência'] },
        { id: 's10_lembretes', tipo: 'escolha_unica', label: 'Quer lembretes ativos ou prefere autonomia total?',
          opcoes: ['Lembretes ativos', 'Autonomia total', 'Um pouco de ambos'] },
        { id: 's10_incluir_terceiros', tipo: 'texto_curto', label: 'Alguém deve ser incluído no seu acompanhamento?' },
      ],
    },

    { id: 'sono_quantidade', titulo: 'Quantidade e Qualidade do Sono',
      perguntas: [
        { id: 's11_despertares', tipo: 'escolha_unica', label: 'Quantos despertares noturnos tem habitualmente?',
          opcoes: ['Um ou nenhum despertar noturno', 'Dois despertares noturnos', 'Três ou mais despertares noturnos'] },
        { id: 's11_duracao_despertar', tipo: 'escolha_unica', label: 'Quanto tempo demora a voltar a adormecer após um despertar?',
          opcoes: ['Minutos, volto a dormir rapidamente', 'Até 30 minutos', 'De 30 minutos a 1 hora', 'Mais que 1 hora', 'Não aplica'],
          outro: true },
        { id: 's11_cochilos', tipo: 'escolha_unica', label: 'Costuma fazer "sestas" durante o dia?',
          opcoes: ['Sim diariamente', 'Algumas vezes na semana', 'Raramente', 'Não'] },
        { id: 's11_restaurado', tipo: 'escala', label: 'Sente-se restaurado(a) ao acordar?', min: 1, max: 10 },
        { id: 's11_qualidade_global', tipo: 'escala', label: 'Como classifica a qualidade global do seu sono?', min: 1, max: 10 },
        { id: 's11_sonolencia_dia', tipo: 'escala', label: 'Sente sonolência excessiva durante o dia?', min: 1, max: 10 },
        { id: 's11_hora_deitar', tipo: 'dropdown', label: 'A que horas costuma deitar-se?',
          opcoes: ['Antes das 21h00', '21h00–21h30', '21h30–22h00', '22h00–22h30', '22h30–23h00', '23h00–23h30', '23h30–00h00', '00h00–00h30', '00h30–01h00', 'Depois da 01h00'] },
        { id: 's11_hora_acordar', tipo: 'dropdown', label: 'A que horas costuma acordar?',
          opcoes: ['Antes das 05h00', '05h00–05h30', '05h30–06h00', '06h00–06h30', '06h30–07h00', '07h00–07h30', '07h30–08h00', '08h00–08h30', '08h30–09h00', 'Depois das 09h00'] },
      ],
    },

    { id: 'cronotipo', titulo: 'Cronotipo e Ritmo Circadiano',
      perguntas: [
        { id: 's12_tipo', tipo: 'escolha_unica', label: 'Qual desses tipos se considera?',
          opcoes: ['Definitivamente um tipo matutino', 'Mais matutino que vespertino', 'Mais vespertino que matutino', 'Definitivamente um tipo vespertino'] },
        { id: 's12_jetlag_social', tipo: 'escolha_unica', label: 'Sente jet lag social (grande diferença entre horários de sono em dias de semana vs. fim de semana)?',
          opcoes: ['Regularmente', 'Às vezes', 'Raramente', 'Não'] },
      ],
    },

    { id: 'fatores_psicologicos', titulo: 'Fatores Psicológicos e Emocionais',
      perguntas: [
        { id: 's13_fatores_psicologicos', tipo: 'grelha', titulo: 'Com que frequência sente…',
          colunas: ['Nunca', 'Raramente', 'Frequentemente', 'Quase sempre'],
          linhas: [
            { id: 'ansiedade_noite', label: 'Ansiedade à noite' },
            { id: 'ruminacao', label: 'Preocupações constantes / ruminação' },
            { id: 'humor_deprimido', label: 'Humor deprimido' },
            { id: 'stress_pt', label: 'Stress pós-traumático — pesadelos e/ou hipervigilância' },
            { id: 'irritabilidade', label: 'Irritabilidade' },
            { id: 'falta_energia_motivacao', label: 'Falta de energia ou motivação' },
            { id: 'dificuldade_concentracao', label: 'Dificuldade de concentração' },
            { id: 'alteracoes_apetite', label: 'Alterações de apetite (mais ou menos do que o habitual)' },
            { id: 'perda_interesse', label: 'Perda de interesse em atividades que antes davam prazer' },
          ],
        },
        { id: 's13_desligar_pensamentos', tipo: 'escala', label: 'Classifique a sua capacidade de desligar pensamentos antes de dormir', min: 0, max: 3,
          apoio: '0 = Não consigo desligar, 3 = Quase sempre consigo.' },
      ],
    },

    { id: 'habitos_substancias', titulo: 'Hábitos, Substâncias e Medicamentos',
      perguntas: [
        { id: 's14_habitos_substancias', tipo: 'grelha', titulo: 'Frequência de consumo',
          colunas: ['Nunca', '1-2x por semana', '3-4x por semana', 'Diariamente'],
          linhas: [
            { id: 'cigarro_vaping', label: 'Cigarro/Vaping' },
            { id: 'canabis', label: 'Canábis' },
            { id: 'sedativos', label: 'Sedativos/Hipnóticos' },
            { id: 'psicoestimulantes', label: 'Psicoestimulantes' },
            { id: 'medicacao_cronica', label: 'Medicação crónica' },
          ],
        },
        { id: 's14_nomes_medicamentos', tipo: 'texto_curto', label: 'Se aplicável, especifique os nomes dos medicamentos' },
      ],
    },

    { id: 'sintomas_fisiologia', titulo: 'Doenças, Sintomas e Fisiologia',
      perguntas: [
        { id: 's15_sintomas', tipo: 'grelha', titulo: 'Sente algum destes sintomas?',
          colunas: ['Sim', 'Não', 'Talvez'],
          linhas: [
            { id: 'ronco_apneia', label: 'Ronco, engasgos ou pausas respiratórias' },
            { id: 'pernas_inquietas', label: 'Movimentos involuntários das pernas' },
            { id: 'pesadelos_dor', label: 'Pesadelos ou dores crónicas que acordam' },
            { id: 'urinar_noite', label: 'Acorda para urinar mais de 1x' },
            { id: 'sudorese_noturna', label: 'Sudorese noturna ou variações de temperatura' },
            { id: 'digestivo_congestao', label: 'Hipoglicemia reativa/refluxo/empachamento/congestão nasal' },
            { id: 'bruxismo', label: 'Desgaste dentário/bruxismo' },
          ],
        },
        { id: 's15_diagnostico_relevante', tipo: 'texto_curto', label: 'Diagnóstico médico relevante (se aplicável)' },
      ],
    },

    { id: 'condicoes_quarto', titulo: 'Ambiente e Condições do Quarto',
      perguntas: [
        { id: 's16_condicoes_quarto', tipo: 'grelha', titulo: 'Condições do quarto',
          colunas: ['Adequado', 'Parcial', 'Inadequado'],
          linhas: [
            { id: 'escuridao', label: 'Escuridão do quarto' },
            { id: 'colchao', label: 'Colchão' },
            { id: 'ruido', label: 'Ruído' },
          ],
        },
        { id: 's16_partilha_quarto', tipo: 'escolha_unica', label: 'Partilha o quarto com alguém?',
          opcoes: ['Sim', 'Às vezes', 'Não'] },
      ],
    },

    { id: 'higiene_sono', titulo: 'Higiene do Sono e Estilo de Vida',
      perguntas: [
        { id: 's17_higiene_sono', tipo: 'grelha', titulo: 'Hábitos relacionados com o sono',
          colunas: ['Sim regularmente', 'Às vezes', 'Não'],
          linhas: [
            { id: 'ecras_noite', label: 'Uso de ecrãs antes de dormir' },
            { id: 'exercicio_pre_sono', label: 'Exercício físico antes de dormir' },
            { id: 'luz_natural', label: 'Exposição a luz natural durante o dia' },
            { id: 'meditacao', label: 'Prática de meditação ou relaxamento' },
          ],
        },
      ],
    },
  ],
};
