/* Config de questionário — Pré-Consulta V2. Lido pelo intake-motor.js. Só dados, zero lógica. */

export default {
  id: 'pre_consulta_v2',
  titulo: 'Questionário Pré-Consulta',
  subtitle: 'Avaliação inicial de saúde e estilo de vida',

  seccoes: [
    { id: 'objetivos_expectativas', titulo: 'Objetivos e Expectativas',
      perguntas: [
        { id: 's1_incomoda', tipo: 'escolha_multipla', label: 'O que mais o(a) incomoda atualmente na sua saúde?', max: 3,
          opcoes: ['Excesso de peso ou gordura corporal', 'Dificuldade em controlar o peso', 'Falta de energia ou fadiga', 'Má qualidade do sono', 'Stress ou ansiedade', 'Dificuldade em controlar a alimentação', 'Dores articulares ou musculares', 'Baixa condição física', 'Alterações nas análises clínicas'],
          outro: true },
        { id: 's1_melhorar', tipo: 'escolha_multipla', label: 'O que gostaria principalmente de melhorar?',
          opcoes: ['Perder gordura corporal', 'Reduzir o perímetro abdominal', 'Ganhar massa muscular', 'Melhorar a condição física', 'Dormir melhor', 'Ter mais energia', 'Melhorar a relação com a alimentação', 'Melhorar o controlo dos meus fatores de risco ou doenças', 'Sentir-me melhor física e psicologicamente'],
          outro: true },
        { id: 's1_6meses', tipo: 'texto_curto', label: 'Se este acompanhamento resultar como espera, o que gostaria de conseguir fazer ou sentir daqui a 6 meses?', multilinha: true },
        { id: 's1_receio', tipo: 'texto_curto', label: 'Se nada mudar nos próximos 6–12 meses, o que receia que aconteça ou continue igual?', multilinha: true },
      ],
    },

    { id: 'historia_peso', titulo: 'História do Peso',
      perguntas: [
        { id: 's2_altura', tipo: 'numero', label: 'Altura', apoio: 'cm' },
        { id: 's2_peso_atual', tipo: 'numero', label: 'Peso atual', apoio: 'kg' },
        { id: 's2_peso_maximo', tipo: 'numero', label: 'Peso máximo atingido na vida adulta', apoio: 'kg' },
        { id: 's2_peso_minimo', tipo: 'numero', label: 'Peso mínimo atingido na vida adulta', apoio: 'kg' },
        { id: 's2_peso_melhor', tipo: 'numero', label: 'Em que peso se sentiu melhor na vida adulta?', apoio: 'kg' },
        { id: 's2_peso_satisfatorio', tipo: 'numero', label: 'Qual seria, neste momento, um peso que consideraria satisfatório?', apoio: 'kg' },
        { id: 's2_evolucao_12m', tipo: 'escolha_unica', label: 'Como evoluiu o seu peso nos últimos 12 meses?',
          opcoes: ['Diminuiu', 'Manteve-se aproximadamente estável', 'Aumentou', 'Oscilou bastante', 'Não sei'] },
        { id: 's2_inicio_dificuldade', tipo: 'texto_curto', label: 'Quando começou verdadeiramente a ter dificuldade em controlar o peso?', multilinha: true },
        { id: 's2_acontecimento', tipo: 'escolha_multipla', label: 'Houve algum acontecimento que associe ao aumento ou alteração do peso?',
          opcoes: ['Mudança profissional', 'Alteração importante da rotina', 'Gravidez ou pós-parto', 'Lesão ou doença', 'Interrupção ou redução do exercício', 'Alteração importante do sono', 'Stress ou período emocional difícil', 'Início ou alteração de medicação', 'Deixar de fumar', 'Menopausa/perimenopausa', 'Não identifico nenhum acontecimento'],
          outro: true },
        { id: 's2_tentativas', tipo: 'escolha_unica', label: 'Quantas vezes já tentou perder peso anteriormente?',
          opcoes: ['Nunca', 'Uma vez', 'Algumas vezes', 'Muitas vezes'] },
        { id: 's2_estrategias', tipo: 'escolha_multipla', label: 'Que estratégias já experimentou?',
          opcoes: ['Nunca fiz nenhuma estratégia específica', 'Acompanhamento nutricional', 'Redução de calorias', 'Dieta mediterrânica', 'Low-carb', 'Dieta cetogénica', 'Jejum intermitente', 'Contagem de calorias', 'Substitutos de refeições', 'Medicação para controlo/perda de peso', 'Programa estruturado de exercício'],
          outro: true },
        { id: 's2_funcionou_melhor', tipo: 'texto_curto', label: 'O que considera que funcionou melhor consigo no passado?', multilinha: true },
        { id: 's2_dificuldade_manter', tipo: 'escolha_multipla', label: 'Na sua perspetiva, o que torna mais difícil manter os resultados?', max: 3,
          opcoes: ['Fome', 'Desejos alimentares', 'Episódios de perda de controlo sobre a alimentação', 'Stress ou ansiedade', 'Falta de tempo', 'Cansaço', 'Vida social', 'Férias ou fins de semana', 'Falta de planeamento', 'Estratégias demasiado restritivas', 'Resultados demasiado lentos', 'Lesão ou doença', 'Perda de motivação'],
          outro: true },
      ],
    },

    { id: 'alimentacao_atual', titulo: 'Alimentação Atual',
      perguntas: [
        { id: 's3_refeicoes_dia', tipo: 'escolha_unica', label: 'Quantas refeições costuma fazer por dia?',
          opcoes: ['1–2', '3', '4', '5 ou mais', 'Muito variável'] },
        { id: 's3_comer_apos_jantar', tipo: 'escolha_unica', label: 'Com que frequência costuma comer depois do jantar?',
          opcoes: ['Nunca', 'Raramente', '1–2 vezes por semana', '3–4 vezes por semana', 'Quase diariamente'] },
        { id: 's3_comer_sem_fome', tipo: 'escolha_unica', label: 'Com que frequência sente que come sem ter verdadeira fome física?',
          opcoes: ['Nunca', 'Raramente', 'Algumas vezes por semana', 'Quase diariamente', 'Várias vezes por dia'] },
        { id: 's3_dificuldade_parar', tipo: 'escolha_unica', label: 'Com que frequência sente que começa a comer e tem dificuldade em parar ou controlar a quantidade?',
          opcoes: ['Nunca', 'Raramente', 'Algumas vezes por mês', 'Algumas vezes por semana', 'Quase diariamente'] },
        { id: 's3_situacoes_dificuldade', tipo: 'escolha_multipla', label: 'Em que situações sente maior dificuldade em controlar a alimentação?',
          opcoes: ['Não tenho habitualmente dificuldade', 'Quando estou com stress', 'Quando estou ansioso(a)', 'Quando estou triste ou emocionalmente em baixo', 'Quando estou cansado(a)', 'Quando estou aborrecido(a)', 'Ao final do dia/noite', 'Aos fins de semana', 'Em situações sociais', 'Quando tenho determinados alimentos disponíveis', 'Não identifico um padrão'],
          outro: true },
        { id: 's3_refeicoes_fora', tipo: 'escolha_unica', label: 'Com que frequência faz refeições fora de casa ou encomenda comida?',
          opcoes: ['Raramente ou nunca', '1–2 vezes por semana', '3–4 vezes por semana', '5 ou mais vezes por semana', 'Quase todas as refeições principais'] },
        { id: 's3_restricao_alergia', tipo: 'escolha_multipla', label: 'Tem alguma restrição, alergia ou preferência alimentar?',
          opcoes: ['Nenhuma', 'Intolerância à lactose', 'Doença celíaca/dieta sem glúten por indicação médica', 'Outra alergia alimentar', 'Vegetariano(a)', 'Vegano(a)'],
          outro: true },
        { id: 's3_alimento_nao_abdicar', tipo: 'texto_curto', label: 'Há algum alimento ou hábito alimentar de que não gostaria de abdicar?' },
      ],
    },

    { id: 'atividade_fisica', titulo: 'Atividade Física e Sedentarismo',
      perguntas: [
        { id: 's4_dias_exercicio', tipo: 'numero', label: 'Em quantos dias por semana faz atualmente exercício físico planeado?', min: 0, max: 7 },
        { id: 's4_duracao_sessao', tipo: 'escolha_unica', label: 'Quanto tempo dura habitualmente cada sessão?',
          opcoes: ['Não faço exercício atualmente', 'Menos de 15 min', '15–30 min', '30–45 min', '45–60 min', 'Mais de 60 min'] },
        { id: 's4_tipo_exercicio', tipo: 'escolha_multipla', label: 'Que tipo de exercício pratica atualmente?',
          opcoes: ['Não faço exercício atualmente', 'Caminhada', 'Corrida', 'Ciclismo', 'Natação', 'Ginásio/musculação', 'Exercícios em casa', 'Aulas de grupo', 'Pilates', 'Yoga', 'Desporto coletivo'],
          outro: true },
        { id: 's4_dias_forca', tipo: 'numero', label: 'Quantos dias por semana faz treino de força/musculação?', min: 0, max: 7 },
        { id: 's4_tempo_sentado', tipo: 'escolha_unica', label: 'Num dia habitual, aproximadamente quanto tempo passa sentado(a)?',
          opcoes: ['Menos de 4 h', '4–6 h', '6–8 h', '8–10 h', 'Mais de 10 h', 'Não sei'] },
        { id: 's4_passos_dia', tipo: 'escolha_unica', label: 'Se utiliza relógio ou telemóvel para contar passos, qual é aproximadamente a sua média diária?',
          opcoes: ['Menos de 3.000', '3.000–4.999', '5.000–6.999', '7.000–9.999', '10.000 ou mais', 'Não sei/não monitorizo'] },
        { id: 's4_dor_lesao', tipo: 'escolha_unica', label: 'Tem atualmente alguma dor ou lesão que limite a atividade física?',
          opcoes: ['Não', 'Sim, ligeiramente', 'Sim, moderadamente', 'Sim, muito'] },
        { id: 's4_dor_lesao_texto', tipo: 'escolha_unica', label: 'Se respondeu que tem dor ou lesão, indique onde e de que forma o(a) limita.',
          opcoes: ['Não aplicável'],
          outro: true },
        { id: 's4_indicacao_medica', tipo: 'escolha_unica', label: 'Algum médico lhe recomendou anteriormente evitar ou limitar algum tipo de esforço ou exercício?',
          opcoes: ['Não', 'Sim', 'Não sei'] },
        { id: 's4_dificuldade_exercicio', tipo: 'escolha_multipla', label: 'Qual é atualmente a principal dificuldade para fazer exercício?',
          opcoes: ['Não tenho dificuldade importante', 'Falta de tempo', 'Cansaço', 'Dor ou lesão', 'Falta de motivação', 'Não sei que exercício fazer', 'Não gosto de fazer exercício', 'Horários profissionais', 'Responsabilidades familiares', 'Falta de acesso a local/material'],
          outro: true },
        { id: 's4_dias_realistas', tipo: 'numero', label: 'Realisticamente, quantos dias por semana conseguiria dedicar à atividade física?', min: 1, max: 7 },
        { id: 's4_tempo_realista_sessao', tipo: 'escolha_unica', label: 'Quanto tempo conseguiria realisticamente disponibilizar por sessão?',
          opcoes: ['10–15 min', '15–30 min', '30–45 min', '45–60 min', 'Mais de 60 min'] },
        { id: 's4_atividades_preferidas', tipo: 'escolha_multipla', label: 'Que atividades gostaria mais de fazer?',
          opcoes: ['Caminhar', 'Correr', 'Nadar', 'Ciclismo', 'Ginásio/musculação', 'Exercícios em casa', 'TRX', 'Aulas de grupo', 'Dança', 'Yoga', 'Pilates'],
          outro: true },
      ],
    },

    { id: 'sono', titulo: 'Sono',
      perguntas: [
        { id: 's5_hora_deitar', tipo: 'escolha_unica', label: 'A que horas costuma deitar-se?',
          opcoes: ['Antes das 21h00', '21h00–22h00', '22h00–23h00', '23h00–00h00', '00h00–01h00', 'Depois da 01h00'] },
        { id: 's5_hora_acordar', tipo: 'escolha_unica', label: 'A que horas costuma acordar definitivamente?',
          opcoes: ['Antes das 05h00', '05h00–06h00', '06h00–07h00', '07h00–08h00', '08h00–09h00', 'Depois das 09h00'] },
        { id: 's5_tempo_adormecer', tipo: 'escolha_unica', label: 'Quanto tempo demora habitualmente a adormecer?',
          opcoes: ['Menos de 15 min', '15–30 min', '30–60 min', 'Mais de 60 min'] },
        { id: 's5_despertares', tipo: 'escolha_unica', label: 'Quantas vezes costuma acordar durante a noite?',
          opcoes: ['Nenhuma', '1 vez', '2 vezes', '3 ou mais vezes'] },
        { id: 's5_horas_sono', tipo: 'escolha_unica', label: 'Quantas horas considera que dorme efetivamente numa noite habitual?',
          opcoes: ['Menos de 5 h', '5–6 h', '6–7 h', '7–8 h', '8–9 h', 'Mais de 9 h'] },
        { id: 's5_qualidade_sono', tipo: 'escala', label: 'Como classifica globalmente a qualidade do seu sono?', min: 0, max: 10,
          apoio: '0 = Muito má, 10 = Excelente' },
        { id: 's5_recuperado', tipo: 'escala', label: 'Quando acorda, sente-se recuperado(a)?', min: 0, max: 10,
          apoio: '0 = Nada recuperado(a), 10 = Completamente recuperado(a)' },
        { id: 's5_sonolencia_dia', tipo: 'escolha_unica', label: 'Sente sonolência ou dificuldade em manter-se desperto(a) durante o dia?',
          opcoes: ['Nunca', 'Raramente', 'Algumas vezes', 'Frequentemente'] },
        { id: 's5_sestas', tipo: 'escolha_unica', label: 'Costuma fazer sestas durante o dia?',
          opcoes: ['Nunca', 'Raramente', '1–2 dias por semana', '3–4 dias por semana', 'Quase diariamente'] },
        { id: 's5_ressonar', tipo: 'escolha_unica', label: 'Alguém já lhe disse que ressona intensamente, tem pausas respiratórias ou parece engasgar-se enquanto dorme?',
          opcoes: ['Não', 'Sim', 'Não sei'] },
        { id: 's5_variacao_horarios', tipo: 'escolha_unica', label: 'Os seus horários de sono mudam muito entre dias de trabalho e fins de semana?',
          opcoes: ['Não ou menos de 1 h', 'Cerca de 1–2 h', 'Mais de 2 h', 'Não sei'] },
      ],
    },

    { id: 'saude_atual', titulo: 'Saúde Atual',
      perguntas: [
        { id: 's6_diagnostico', tipo: 'escolha_unica', label: 'Tem algum diagnóstico médico relevante?',
          opcoes: ['Não', 'Sim'] },
        { id: 's6_diagnostico_texto', tipo: 'escolha_unica', label: 'Se respondeu Sim, indique qual/quais.',
          opcoes: ['Não aplicável'],
          outro: true },
        { id: 's6_medicacao', tipo: 'escolha_unica', label: 'Toma medicação regularmente?',
          opcoes: ['Não', 'Sim'] },
        { id: 's6_medicacao_texto', tipo: 'escolha_unica', label: 'Se respondeu Sim, indique qual/quais.',
          opcoes: ['Não aplicável'],
          outro: true },
        { id: 's6_limitacao', tipo: 'escolha_unica', label: 'Tem atualmente alguma condição, sintoma ou limitação física que considere importante para planear exercício ou alterações do estilo de vida?',
          opcoes: ['Não', 'Sim'] },
        { id: 's6_limitacao_texto', tipo: 'escolha_unica', label: 'Se respondeu Sim, descreva brevemente.',
          opcoes: ['Não aplicável'],
          outro: true },
      ],
    },

    { id: 'habitos', titulo: 'Hábitos',
      perguntas: [
        { id: 's7_agua', tipo: 'escolha_unica', label: 'Aproximadamente quanta água bebe habitualmente por dia?',
          opcoes: ['Menos de 1 L', '1–1,5 L', '1,5–2 L', '2–3 L', 'Mais de 3 L'] },
        { id: 's7_cafeina', tipo: 'escolha_unica', label: 'Quantos cafés ou outras bebidas com cafeína consome habitualmente por dia?',
          opcoes: ['Nenhum', '1', '2', '3', '4 ou mais'] },
        { id: 's7_alcool', tipo: 'escolha_unica', label: 'Com que frequência consome bebidas alcoólicas?',
          opcoes: ['Nunca', 'Menos de 1 dia por semana', '1–2 dias por semana', '3–4 dias por semana', '5 ou mais dias por semana'] },
        { id: 's7_nicotina', tipo: 'escolha_unica', label: 'Fuma ou utiliza atualmente produtos com nicotina?',
          opcoes: ['Não, nunca utilizei regularmente', 'Não, sou ex-fumador(a)/ex-utilizador(a)', 'Sim, ocasionalmente', 'Sim, diariamente'] },
      ],
    },

    { id: 'stress_contexto', titulo: 'Stress, Contexto e Apoio',
      perguntas: [
        { id: 's8_stress', tipo: 'escala', label: 'Como classifica o seu nível habitual de stress?', min: 0, max: 10,
          apoio: '0 = Nenhum, 10 = Extremamente elevado' },
        { id: 's8_influencia_alimentacao', tipo: 'escolha_unica', label: 'Sente que o stress, ansiedade, tristeza ou cansaço influenciam a sua alimentação?',
          opcoes: ['Não', 'Raramente', 'Algumas vezes', 'Frequentemente', 'Muito frequentemente'] },
        { id: 's8_apoio_proximos', tipo: 'escolha_unica', label: 'Sente apoio das pessoas que lhe são próximas para fazer estas mudanças?',
          opcoes: ['Muito', 'Razoavelmente', 'Pouco', 'Nenhum', 'Não se aplica'] },
        { id: 's8_horario_profissional', tipo: 'escolha_unica', label: 'Qual é o seu horário profissional habitual?',
          opcoes: ['Horário fixo diurno', 'Trabalho por turnos', 'Trabalho predominantemente noturno', 'Horário irregular', 'Não trabalho atualmente'] },
      ],
    },

    { id: 'motivacao_implementacao', titulo: 'Motivação e Implementação',
      perguntas: [
        { id: 's9_prontidao', tipo: 'escala', label: 'Neste momento, quão preparado(a) se sente para fazer mudanças no seu estilo de vida?', min: 0, max: 10,
          apoio: '0 = Nada preparado(a), 10 = Totalmente preparado(a)' },
        { id: 's9_confianca', tipo: 'escala', label: 'Quanta confiança tem de conseguir manter essas mudanças durante pelo menos 6 meses?', min: 0, max: 10,
          apoio: '0 = Nenhuma confiança, 10 = Total confiança' },
        { id: 's9_confianca_subir', tipo: 'texto_curto', label: 'O que faria essa confiança aumentar 2 pontos?' },
        { id: 's9_mudanca_semana', tipo: 'escolha_unica', label: 'Se tivesse de escolher apenas UMA mudança para começar esta semana, qual escolheria?',
          opcoes: ['Melhorar o sono', 'Caminhar mais', 'Começar a fazer exercício', 'Fazer exercício com maior regularidade', 'Começar treino de força', 'Melhorar a alimentação', 'Reduzir doces/snacks', 'Beber mais água', 'Organizar melhor as refeições', 'Reduzir álcool', 'Passar menos tempo sentado(a)'],
          outro: true },
        { id: 's9_obstaculo', tipo: 'escolha_multipla', label: 'Qual pensa ser o principal obstáculo para conseguir começar?',
          opcoes: ['Não antecipo nenhuma dificuldade importante', 'Falta de tempo', 'Cansaço', 'Trabalho', 'Responsabilidades familiares', 'Eventos sociais', 'Fome/desejos alimentares', 'Dor ou limitação física', 'Falta de motivação', 'Falta de organização'],
          outro: true },
      ],
    },

    { id: 'final', titulo: 'Final',
      perguntas: [
        { id: 's10_algo_mais', tipo: 'texto_curto', label: 'Há alguma coisa importante sobre a sua saúde, rotina ou objetivos que não lhe perguntámos e que gostaria que soubéssemos antes da consulta?', multilinha: true },
      ],
    },
  ],
};
